version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cinnamon-qa-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - cinnamon-qa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Commander - Web UI for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cinnamon-qa-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - cinnamon-qa-network

  # Playwright-MCP Test Container
  playwright-mcp-test:
    image: mcr.microsoft.com/playwright/mcp:latest
    container_name: cinnamon-qa-playwright-mcp-test
    restart: "no"
    ports:
      - "3000:3000"
    command: ["--headless", "--host", "0.0.0.0", "--port", "3000", "--isolated"]
    environment:
      - CONTAINER_POOL_ID=test-container-001
    networks:
      - cinnamon-qa-network
    mem_limit: 512m
    cpus: 0.5

volumes:
  redis_data:
    driver: local

networks:
  cinnamon-qa-network:
    driver: bridge